#!/bin/bash

# variables
USER=ismail
ARIA_BIN=/usr/bin/aria2c
KEY=1234abcd
SEGMENTS=($(echo $2 | tr ":" "\n"))
USER_ID=${SEGMENTS[0]}
FEEDBACK_ID=${SEGMENTS[1]}
FOLDER=${SEGMENTS[2]}
STORAGE="/var/www/maiven-bot/storage"
FILEPATH="$STORAGE/$FOLDER"
FILENAME="$FOLDER.zip"

# 1. run aria2c
$ARIA_BIN -s 10 -x 10 -d $STORAGE -i $1

# 2. compress files / delete tmp files
zip -q -r "$STORAGE/$FILENAME" $FILEPATH
rm -rf $FILEPATH

# 3. call webhook
curl -s "https://5cb6-105-67-135-83.ngrok-free.app/api/callback?key=$KEY&user_id=$USER_ID&mid=$FEEDBACK_ID&filename=$FILENAME"
